// components/brand.js
export const BRAND = {
  name: "SaharNail",
  phone: "+31 617802068",
  email: "nailbysaharrrr@gmail.com",
  instagram: "https://www.instagram.com/nailbysaharrrr/",
  address: "Walt Disneyplantsoen 80A, 1325 SX Almere, NL",
  bookingUrl: "https://saharnail.simplybook.it/v2/#book",
  logo: "/images/logo.png",
};

// هر چیزی که لازم شد اینجا عوض کن (ادمین ساده)
export const T = {
  en: {
    switch: "NL",
    heroTitle: "Professional Manicure & Pedicure",
    heroSubtitle: "Minimal, elegant & long-lasting results.",
    cta: "Book Online",
    addressLine: (addr, phone) => `${addr} • Phone: ${phone}`,
    gallery: "Gallery",
    services: "Services",
    pricing: "Pricing",
    about: "About",
    aboutText:
      "I’m Sahar — a nail artist focused on clean, minimal and elegant looks using high-quality materials and strict hygiene.",
    contact: "Contact",
    address: "Address",
    phone: "Phone",
    email: "Email",
    insta: "Instagram",
    footerPrivacy: "Privacy",
    footerTerms: "Terms",
    bookThis: "Book",
    duration: "Duration",
  },
  nl: {
    switch: "EN",
    heroTitle: "Professionele Manicure & Pedicure",
    heroSubtitle: "Minimalistisch, elegant en duurzaam resultaat.",
    cta: "Online Boeken",
    addressLine: (addr, phone) => `${addr} • Telefoon: ${phone}`,
    gallery: "Galerij",
    services: "Diensten",
    pricing: "Prijzen",
    about: "Over",
    aboutText:
      "Ik ben Sahar — nagelstyliste met focus op strakke, minimalistische en elegante looks met hoogwaardige materialen en hygiëne.",
    contact: "Contact",
    address: "Adres",
    phone: "Telefoon",
    email: "E-mail",
    insta: "Instagram",
    footerPrivacy: "Privacy",
    footerTerms: "Voorwaarden",
    bookThis: "Boeken",
    duration: "Duur",
  },
};

// لیست سرویس‌ها (قابل ویرایش)
// اگر قیمت داری، یک فیلد price هم اضافه کن.
export const SERVICES = [
  { id: "biab", title: "BIAB Nails and Manicure",
    desc: "Strengthen and beautify your natural nails with BIAB, finished with a flawless manicure.",
    duration: "1 hr" },
  { id: "new-removal", title: "New set + combi manicure + removal",
    desc: "Waterless treatment focusing on nail & cuticle care, shaping, polish—no soak time.",
    duration: "1 hr 40 mins" },
  { id: "new-gel", title: "New set + Combi manicure + gel polish", duration: "1 hr 30 mins" },
  { id: "new-gel-removal", title: "New set + Combi manicure + gel polish + removal", duration: "1 hr 40 mins" },
  { id: "new-french", title: "New set + French design", duration: "1 hr 40 mins" },
  { id: "new-french-removal", title: "New set + French design + removal", duration: "1 hr 40 mins" },
  { id: "dry-combi", title: "Dry combi pedicure or manicure and nail shaping", duration: "30 mins" },
  { id: "spa-pedi", title: "Spa pedicure", duration: "45 mins" },
  { id: "coat-removal", title: "Gel polish or BIAB coating without full pedicure + removal", duration: "1 hr" },
  { id: "coat-french", title: "Gel polish/BIAB without full pedicure + French", duration: "1 hr" },
  { id: "coat-french-rem", title: "Gel polish/BIAB without full pedicure + French + removal", duration: "1 hr 5 mins" },
  { id: "spa-biab", title: "Spa pedicure + gel polish or BIAB", duration: "1 hr 15 mins" },
  { id: "spa-biab-rem", title: "Spa pedicure + gel polish or BIAB + removal", duration: "1 hr 20 mins" },
  { id: "spa-biab-french", title: "Spa pedicure + gel polish or BIAB + French design", duration: "1 hr 30 mins" },
  { id: "spa-biab-french-rem", title: "Spa pedicure + gel polish or BIAB + French + removal", duration: "1 hr 35 mins" },
  { id: "ext-combi", title: "Nail extension + combi manicure", duration: "1 hr 50 mins" },
  { id: "ext-gel", title: "Nail extension + combi manicure + gel polish", duration: "2 hr" },
  { id: "ext-french", title: "Nail extension + combi manicure + French", duration: "2 hr 10 mins" },
  { id: "removal-only", title: "Removal without manicure", duration: "30 mins" },
  { id: "removal-combi", title: "Removal + combi manicure or pedicure", duration: "50 mins" },
];
